### ISSUE TITLE
alignments for read non-consecutive in output

### ISSUE THREAD

**Issue by Blahah** [amplab/snap#44] opened 2015-01-15 21:31 UTC
Most aligners guarantee that all alignments for a read will be consecutive in the output. Indeed, SNAP does this the vast majority of the time, but occasionally outputs alignments for a read non-consecutively.

I can provide an example dataset to reconstruct the problem if necessary.

**Comment by rob-p** [comment] 2015-02-08 18:28
Hi guys,

  I just wanted to let you know that I'm running up against the same issue.  I'd like to test (and potentially use) SNAP, but many of the tools I'm [testing](https://github.com/adarob/eXpress) or [developing](https://github.com/kingsfordgroup/sailfish/tree/develop) require all of the alignments for a particular read to be adjacent in the output file.  Furthermore, `samtools sort -n` doesn't really work well here, because it [destroys the adjacency of the alignment records for paired-end reads](https://www.biostars.org/p/130022/).  Let me know if there's anything I can do to help track down and resolve the source of this bug.

**Comment by bolosky** [comment] 2015-02-09 16:04
It’s not a bug in the sense that I never intended SNAP to have that property.  It sounds like maybe it needs to have it, though.

The reason that it’s happening is the way that the output system works.  It builds up batches of aligned reads ready to write from each aligner thread, and then when a batch is full, it sends the whole thing to the writer to be written.   When the alignments from a particular read happen to cross a batch boundary, then they may well be split in the output.   SNAP’s sorting may also rearrange reads that are aligned to the same location.

I’ll look at it and try to figure out how much work it would be change.

--Bill

**Comment by bolosky** [comment] 2015-02-26 22:44
Fixed in 1.0dev.68.  This was a royal pain to get right, but I think it's OK now.  At least, it seems to generate exactly the same alignments as before, but they're no longer ever out of order.

**Closed by bolosky** 2015-02-26 22:44 UTC

**Comment by rob-p** [comment] 2015-02-26 23:10
Excellent, @bolosky; thanks!  This property is very important in the context in which we're using it, as all of the alignments for a read need to occur together in the file so that we can resolve the origin of multi-mapping reads "online".  When some alignments for reads are not contiguous, there is no way to figure out the entire set without look-ahead  parsing, which would everything *and* slow it down.  Hopefully @Blahah and I can give this fix a try soon!
